name: Build and push to iona's container registry
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  cd:
    name: Build and push to iona's container registry
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'arduino/setup-task@v1'
        with:
          version: 3.x
      - uses: 'hiberbee/github-action-skaffold@1.12.0'
        with:
          skaffold-version: 1.37.0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/871349271977/locations/global/workloadIdentityPools/github-oidc-1/providers/github-provider'
          service_account: 'gha-cd-apikeystore@iona-1.iam.gserviceaccount.com'

      - uses: 'docker/login-action@v1'
        with:
          registry: 'eu.gcr.io/iona-1' # or REGION-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io/iona-1


      - id: build_id
        name: Generate build ID
        run: |
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            calver=$(date +%g.%m%d).${{ github.run_number }}
            buildno=${{ github.run_number }}

            # echo "::set-output name=BUILD_ID::${branch}-${sha}-${calver}"
            echo "::set-output name=BUILD_ID::${branch}-${buildno}"

      - name: Build and publish container image with tag
        run: |
            export SKAFFOLD_DEFAULT_REPO=eu.gcr.io/iona-1
            task cd-build TAG=${BUILD_ID} PROFILE=push
